### ISSUE TITLE
ReduceLROnPlateau is not importing from keras.callbacks

### ISSUE THREAD

**Issue by rlkelly** [basveeling/wavenet#1]
ImportError: cannot import name ReduceLROnPlateau

It appears I am having trouble with the modified install of keras, I'm going to try again in a virtual environment and see if that's the problem.

**Comment by rlkelly** [comment]
It appears that was the issue, It might be helpful to put a note about using a virtual environment in the quickstart guide.

**Comment by huyouare** [comment]
How did the virtual env help with installation? What steps did you take?

**Comment by muzaluisa** [comment]
Hey, so what should be done in this case about importing to make it work with virtualenv?)

**Comment by R-Gaurav** [comment]
hello all, I am also getting "ImportError: cannot import name ReduceLROnPlateau". I tried installing a new tensorflow environment through conda and the installing keras via pip in the same environment. I also referred https://github.com/basveeling/wavenet/issues/5. But the issue still persists. Can some one help? Thanks for your interest.

**Comment by anewlearner** [comment]
@R-Gaurav 
Have you solved it?

**Comment by anewlearner** [comment]
@R-Gaurav 
1. Update keras.
2. from keras.callbacks import ReduceLROnPlateau 
ReduceLROnPlateau is not imported from `optimizers` but `callbacks`.

**Comment by JagadishSivakumar** [comment]
This worked for me, 
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
