### ISSUE TITLE
Fix: Skip connections have separate 1x1 convolutions from the residual output.

### ISSUE THREAD

**Issue by basveeling** [basveeling/wavenet#10]
After some correspondence with the authors it turns out that the skip connections are parameterized by a 1x1 convolution, separate from the one that goes into the add block. This should be an easy fix but could potentially explain poor training results before.

**Comment by jfsantos** [comment]
All this means is that each `skip_out` should be the output of another Conv1D layer instead of being the same as `x`, right? I'll submit a PR soon.
