### ISSUE TITLE
Exception: You are trying to load a weight file containing 69 layers into a model with 90 layers.

### ISSUE THREAD

**Issue by mayowaosibodu** [basveeling/wavenet#12]
Here's the issue I encounter:

wavenet$ KERAS_BACKEND=theano python wavenet.py predict with models/run_20160914_113209/config.json predict_seconds=1 sample_temperature=0.001
WARNING (theano.configdefaults): Only clang++ is supported. With g++, we end up with strange g++/OSX bugs.
Using Theano backend.
WARNING - root - Changed type of config entry "run_dir" from NoneType to unicode
WARNING - root - Changed type of config entry "optimizer.epsilon" from NoneType to float
INFO - wavenet - Running command 'predict'
WARNING - wavenet - No observers have been added to this run
INFO - wavenet - Started
INFO - predict - Using checkpoint from epoch: 37
INFO - predict - Saving to "models/run_20160914_113209/samples/sample_epoch-00037_01s__sample-temp-0.001_seed-920639969.wav"
INFO - build_model - Receptive Field: 4095 (928ms)
ERROR - wavenet - Failed after 0:00:03!
Traceback (most recent calls WITHOUT Sacred internals):
  File "wavenet.py", line 316, in predict
    model.load_weights(os.path.join(checkpoint_dir, last_checkpoint))
  File "/Users/m/virtualenvs/wavenet/lib/python2.7/site-packages/keras/engine/topology.py", line 2500, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/Users/m/virtualenvs/wavenet/lib/python2.7/site-packages/keras/engine/topology.py", line 2552, in load_weights_from_hdf5_group
    str(len(flattened_layers)) + ' layers.')
Exception: You are trying to load a weight file containing 69 layers into a model with 90 layers.

not sure what the problem is, but i think it might have to do with the model checkpoint in use?

**Comment by jtoytkt** [comment]
I have the same problem，maybe conf and model not match?

**Comment by basveeling** [comment]
Thanks! I uploaded a new model trained on VCTK :).
