### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by ShawnWongMILab** [basveeling/wavenet#15]
Hi guys!  Do u know how to  extract linguistic features from the text? Or is there any tool could do that easily?

**Comment by tiberiu44** [comment]
Hi and sorry for the late reply. You could try slp.racai.ro. It supports English and Romanian. I am also working on a wavenet implementation, but I used C++ and CUDA, because tensorflow is way to slow for the machine I am using. Let me know if you need any ther help.

Best,
Tibi
