### ISSUE TITLE
Error with 'pip install -r requirements.txt'

### ISSUE THREAD

**Issue by ydwang72** [basveeling/wavenet#16]
with Ubuntu 14, as I am following these steps:
## \- Activate a new virtualenv (recommended):
- pip install virtualenv
- mkdir ~/virtualenvs && cd ~/virtualenvs
- virtualenv wavenet
- source wavenet/bin/activate
## \- Clone and install requirements:
- cd ~
- git clone https://github.com/basveeling/wavenet.git
- cd wavenet
  **\- pip install -r requirements.txt**

ValueError: ('Expected version spec in', 'picklable_itertools~=0.1.1', 'at', '~=0.1.1')

**Comment by muzaluisa** [comment]
When I was installing out of anaconda, I had the same error. 

With conda installation it worked fine
conda create -n wavenet numpy

**Comment by basveeling** [comment]
What version of pip are you using?
