### ISSUE TITLE
How long should it take to train a new model ? How much data do I need ?

### ISSUE THREAD

**Issue by TristeFigure** [basveeling/wavenet#3]
Hi,

I'm trying to train a new model out of sheer curiosity (and a geat deal of naiveté), and I was wondering how long should I expect the training to last, with, ahem, a 2015 Macbook Pro (Intel Iris Graphics 6100 1536 Mo) ?
I've just a very simple background in machine learning and have never done deep learning, and I was wondering if it was possible (i can be very patient and wait for a couple months if necessary).
Also, how many epoch should I do ? Is a single album enough as input data ?

**Comment by basveeling** [comment]
Hi, it all depends on the exact problem you're trying to solve, and the best way to figure out how long it would take is by training a very small model for one epoch and extrapolating the results. If you want to do something with new music generation then one album will not be enough. Try looking at the http://www.deeplearningbook.org if you want to get a better understanding of deep learning. Good luck!
