### ISSUE TITLE
ImportError: cannot import name ReduceLROnPlateau

### ISSUE THREAD

**Issue by huyouare** [basveeling/wavenet#5]
ReduceLROnPlateau seems to be in https://github.com/basveeling/keras/tree/callbacks but not https://github.com/basveeling/keras/tree/wavenet

**Comment by basveeling** [comment]
It is there: https://github.com/basveeling/keras/blob/wavenet/keras/callbacks.py#L537
If you're running into any import error issues; have you tried creating a new virtualenv to install the requirements?

**Comment by huyouare** [comment]
Yep, tried it again and worked. Seem like I had issues with my pip version and an existing venv. Thanks!

**Comment by MuhammadKA** [comment]
@huyouare 
Can you please tell me the pip version which solved this problem?
because I am facing the same problem with keras 1. 
When I use keras 2 the error disappears. Do you have any idea why this is happening?
