### ISSUE TITLE
models/run directory name incompatible with Windows

### ISSUE THREAD

**Issue by jrao1** [basveeling/wavenet#6]
This makes it impossible to checkout the project under Windows. I would suggest removing "-" and ":" from the directory name and change line 336 of wavenet.py to 

`        run_dir = os.path.join('models', datetime.datetime.now().strftime('run_%Y%m%d_%H%M%S'))`

**Comment by basveeling** [comment]
Thanks for the tip! Let me know if the last fix works, and let me know if you run into any other problems on windows.
