### ISSUE TITLE
Undocumented dependencies on 'sacred', 'tqdm'

### ISSUE THREAD

**Issue by danbri** [basveeling/wavenet#8]
These seem to be necessary for sampling.

**Comment by basveeling** [comment]
Running `pip install -r requirements.txt` should take care of this.  Do you think it will be helpful to  mention all the dependencies in the readme?

**Comment by danbri** [comment]
Hmm odd I thought I had done that. It's possible I ran it in a different virtualenv, closing this issue!

**Comment by basveeling** [comment]
I've added a bit more details to the installation section, hope that will help future users.
