### ISSUE TITLE
TTS synthesis

### ISSUE THREAD

**Issue by yhifny** [basveeling/wavenet#9]
Can you show how to use this code for Text to Speech (TTS) synthesis?

**Comment by basveeling** [comment]
This is not in the pipeline right now. There are many ways to do this, but to get good quality you probably need strong guiding features as conditional input for the WaveNet. 

If you're looking to get into the nitty gritty: check out the paper by Deepmind. They use a battery of local features for their TTS experiments. Some of them are generated by a program that generates linguistic features, and some with custom neural networks that for example generate the pitch of the voice.
